language: node_js
node_js:
  - "stable"
cache:
    directories:
        - "node_modules"
script: npm run build
env:
    global:
        - FTP_HOST=host
        - FTP_USER=user
        - FTP_PASSWORD=password